sudo: required

language: node_js

node_js:
  - "0.12"

before_install:
  - "sudo pip install --upgrade pip"
  - "sudo pip install selenium"
  - "sudo pip install behave"
  
install:
  - "npm install"
  - "gulp bundle"

# Travis supports running a real browser (Firefox) with a virtual screen
# https://en.wikipedia.org/wiki/Xvfb
# http://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0" 
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
script: 
  - "PGDIR=`pwd`"
  - "cd tests/behave"
  - "TARGET=file://$PGDIR behave"

branches:
  only:
    - adding-tests-refact-md

notifications:
  email:
    - zhy19@pitt.edu